### ISSUE TITLE
Zalgo

### ISSUE THREAD

**Issue by TehShrike** [mafintosh/mutexify#1]
Would you be open to a pull request that changed the function invocations to use `process.nextTick` or [asap](https://www.npmjs.com/package/asap) to avoid having callbacks called in the same stack as the previous function?

**Comment by mafintosh** [comment]
hmm this module isn't really doing async stuff so that sounds a bit weird to me. you might convince me though if you tell me what the use-case is for this change? :)

**Comment by TehShrike** [comment]
mutexify *sometimes* acts asynchronously - right now if the lock is free, it calls the function right away - but if it is locked, it queues up the function to be run in a potentially different stack.  To the caller, it is non-deterministic whether or the function will be called in the same stack or not.  (Zalgo is a reference to [this post by isaacs](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony).)

I agree with Havoc that [not knowing whether or not your callback function will be called in the same stack is undesirable](http://blog.ometer.com/2011/07/24/callbacks-synchronous-and-asynchronous/).

Right now I'm wrapping every mutexify interaction with `process.nextTick` in [read-write-lock](https://github.com/TehShrike/read-write-lock/blob/master/index.js#L32) so that I can guarantee that callbacks are always called in a different stack.  I think it would be a better fit in mutexify, though, if you're interested.

**Comment by mafintosh** [comment]
Good points. Send me a PR and I'll merge it.
