### ISSUE TITLE
TypeError: used is not a function When process under high load

### ISSUE THREAD

**Issue by mastilver** [mafintosh/mutexify#7]
First of all, thank you for this module and your work with hypercore!!

On one of my unit test, I'm running 4000 webpack compilation and locks, it's quite an unusual setup and I would understand if you close that issue :)

The issue doesn't appear on `v1.0.1`, I believe it's been introduced by: https://github.com/mafintosh/mutexify/commit/217ebcbf561ae0a157293a987ca65f292a7928a5

before https://github.com/mafintosh/mutexify/commit/217ebcbf561ae0a157293a987ca65f292a7928a5: https://travis-ci.org/danethurber/webpack-manifest-plugin/builds/273976849?utm_source=github_status&utm_medium=notification

after https://github.com/mafintosh/mutexify/commit/217ebcbf561ae0a157293a987ca65f292a7928a5: https://travis-ci.org/danethurber/webpack-manifest-plugin/builds/273970831?utm_source=github_status&utm_medium=notification

I believe this have to do this v8 garbage collector

**Comment by mafintosh** [comment]
You are getting that error because you are calling the mutex function with something that isn't a function.

**Comment by mastilver** [comment]
I believe I'm calling it correctly: https://github.com/danethurber/webpack-manifest-plugin/pull/85/files#diff-f85c36a1cc8952fb5e6fc7200a89ceaaR184

The only difference between the randomly failing builds and the correct one is this line: https://github.com/danethurber/webpack-manifest-plugin/pull/85/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R44
